### ISSUE TITLE
Put configuration parameters in a config file

### ISSUE THREAD

**Issue by ljdursi** [CanDIG/htsget_app#1]
There's a number of ways this can be done, but a simple and common way to do this is with `configparser`: https://docs.python.org/3/library/configparser.html

Here's an example of combining configparser with argparse to allow the config parameters to be overridden on the command line: https://stackoverflow.com/questions/3609852/which-is-the-best-way-to-allow-configuration-options-be-overridden-at-the-comman

**Comment by zhengwin** [comment]
/home/jackson/Documents/GitHub/htsget_app/config.ini
