### ISSUE TITLE
Create a README.md for the repo

### ISSUE THREAD

**Issue by ljdursi** [CanDIG/htsget_app#13]
- [x] Create a README which describes this repo as an implementation of the HTSGET protocol (and link to it), with a very brief description of the features and how to run it.  You can, but needn't, reference the python model service (https://github.com/CanDIG/python_model_service) and use its README as a model.
- [x] Add badges for travis, pyup, and code factor.  You can see how that's done in the python model service README; I've activated this repo for those services.
- [x] When the docker container is successfully being built we can also include the badge for quay.io.

**Comment by ljdursi** [comment]
Oh forgot, should probably credit GEl htsget too since that was a starting point https://github.com/genomicsengland/gel-htsget

**Comment by zhengwin** [comment]
./readme.md
