### ISSUE TITLE
Add python packaging for package

### ISSUE THREAD

**Issue by ljdursi** [CanDIG/htsget_app#2]
Following python_model_service, create directory structure and a `setup.py` such that one can do the following steps:

* `virtualenv htsenv`
* `source htsenv/bin/activate`
* `python setup.py install`

and have the htsget server installed in the local python environment.  This will require #1 to be complete so that one can change configuration parameters without having to reinstall.

**Comment by zhengwin** [comment]
/home/jackson/Documents/GitHub/htsget_app/setup.py
