### ISSUE TITLE
setup.py file is missing?

### ISSUE THREAD

**Issue by rjiang9** [CanDIG/htsget_app#335]
Hi dev folks,

It looks the setup.py file is missing from the repo. Just can't follow the `README.md` to install on local (no in docker). 

Best,
Ray

**Comment by daisieh** [comment]
I don't think that's possible to do anymore, or at least we haven't supported it in years. I think that the README is woefully out of date, apologies!

**Comment by rjiang9** [comment]
> I don't think that's possible to do anymore, or at least we haven't supported it in years. I think that the README is woefully out of date, apologies!

It looks it's fine without it when the stack working as docker containers. This ticket can be closed. Thanks @daisieh .
