### ISSUE TITLE
The application does not seem to be following some of the htsget specs

### ISSUE THREAD

**Issue by jimmyhli** [CanDIG/htsget_app#85]
The `htsget` spec defines that 

- the `id` should pass as a URL parameter, e.g., `/data/<id>`, but this application considers `id` a query string parameter, which treats it as `/data?id=`.

- parameters should be written in camelCase, such as `referenceName`, the application spec writes it as `reference_name`.

- server should accept `chr1`, `1` both as valid reference to chromosome 1, yet the server only accepts `1`. The spec also indicates that `chr` is of type `int`, while it should be of type `string`.

**Comment by daisieh** [comment]
These are all fixed.
