### ISSUE TITLE
The /variants endpoint is not handling the request correctly

### ISSUE THREAD

**Issue by jimmyhli** [CanDIG/htsget_app#95]
It looks like it doesn't support search for VCFs across multiple chromosomes; the implementation seems to assume that one VCF file can only contain records from 1 chromosome.

E.g., for the following sample VCF File (headers are stripped)

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	217-70-3296_sample_1
1	76569151	.	C	A	.	PASS	.	GT	0/0
1	82441079	.	C	T	.	PASS	.	GT	0/0
3	46018344	.	G	A	.	PASS	.	GT	1/1
21	34609505	.	G	A	.	PASS	.	GT	1/1
```

If you do a `/variants` search on this, it will return the `referenceName` as `None`, start as the first row, which is `76569151`, and end as the last row, which is `34609505`, even though they belong to different chromosomes

**Comment by daisieh** [comment]
Going to assume that this is no longer relevant.
